{
  "user_service": {
    "timestamp": "2025-05-15T09:35:41.735618",
    "status": "healthy",
    "response_time": 0.001818
  },
  "order_service": {
    "timestamp": "2025-05-15T09:35:41.735618",
    "status": "unhealthy",
    "error": "HTTPConnectionPool(host='service_b', port=5000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffffaa9b52e0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
  },
  "inventory_service": {
    "timestamp": "2025-05-15T09:35:41.735618",
    "status": "healthy",
    "response_time": 0.001653
  },
  "notification_service": {
    "timestamp": "2025-05-15T09:35:41.735618",
    "status": "healthy",
    "response_time": 0.001476
  }
}