{
  "user_service": {
    "timestamp": "2025-05-09T09:10:14.936082",
    "status": "unhealthy",
    "error": "HTTPConnectionPool(host='service_a', port=5000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffffa6ff60a0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
  },
  "order_service": {
    "timestamp": "2025-05-09T09:10:14.936082",
    "status": "unhealthy",
    "error": "HTTPConnectionPool(host='service_b', port=5000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffffa6feed90>: Failed to establish a new connection: [Errno 111] Connection refused'))"
  },
  "inventory_service": {
    "timestamp": "2025-05-09T09:10:14.936082",
    "status": "unhealthy",
    "error": "HTTPConnectionPool(host='service_c', port=5000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffffa6fee1c0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
  },
  "notification_service": {
    "timestamp": "2025-05-09T09:10:14.936082",
    "status": "unhealthy",
    "error": "HTTPConnectionPool(host='service_d', port=5000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffffa6fdf1c0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
  }
}